MODEL: LightCNN-29v4
LR: 0.005
PRE_LR: 1
MOENTUM: 0.9
CUDA: True
WEIGHT_DECAY: 0.0001
ROOT_PATH: datasets/Tufts
BATH_SIZE: 128
WORKERS: 1
T: 0.1
ALPHA: 0.3
BETA: 0.00006
FC2_EPOCHS: 10
DROPOUT_RATE: [0.7,0.6,0.5,0.9]
MAX_DROPOUT: [0.95,0.95,0.95,0.95]
EPOCHS: 50
TAU: 0.4
DATASET: Tufts
PRE_PROTOCOL: ['label']
PROTOCOLS: ['label','imglist']
UNLABEL: ['unlabel']
OUTPUT_PATH: logs/Tufts/train/
VAL_PATH: config/Tufts_val.yml
VAL_FREQ: 3
PRINT_FREQ: 100
WEIGHTS: model/weight/LightCNN-V4_checkpoint.pth.tar
PERTRAIN: True
ATTACK_HEAD: attack

ATTACK_PATH: datasets/Tufts/Protocol/attack_imglist.txt
UNLABEL_PROTOCOL: datasets/Tufts/Protocol/imglist.txt
ADJUST_EPOCH: 10